name: Notify Teams of Release Status
description: Notify a Microsoft Teams channel of the success or failure of a release

inputs:
  app-name:
    required: true
    description: The name for the application.
  version:
    required: true
    description: The version of the application.
  image:
    required: false 
    description: The name of the container image created and pushed to a registry
  status:
    required: true
    default: failure
    description: Expects either 'success' or 'failure' values
  teams-channel-connector-hash:
    required: false
    description: The hash value for the Teams channel connector.

runs:
  using: "composite"
  steps:
    - name: Notify of Success
      if: ${{ (inputs.status == 'success') && (inputs.teams-channel-connector-hash != '') }}
      shell: bash
      run: |
        curl -H 'Content-Type: application/json' -d '{"text": "<div style=\"border-style: solid; border-width: thick; background-color: #47d247; color: white; border-radius: 10px; padding-bottom: 10px; margin-left: 10px; margin-right: 10px; border-color: green; text-align: center \">
            <h1 style=\"font-size: 2em;\">Success</h1>
              <div>
                <strong>Application: ${{ inputs.app-name }}:${{ inputs.version }} released successfully!</strong>
                <p>${{ inputs.image }}</p>
              </div>
          </div>"
          }' https://telicentio.webhook.office.com/webhookb2/${{ inputs.teams-channel-connector-hash }}
    - name: Notify of failure
      if: ${{ (inputs.status == 'failure') && (inputs.teams-channel-connector-hash != '') }}
      shell: bash
      run: |
        curl -H 'Content-Type: application/json' -d '{"text":"
          <div style=\"border-style: solid; border-width: thick; border-color: red; text-align: center; background-color: #ee8787; color: white; border-radius: 10px; padding-bottom: 20px; margin-left: 10px; margin-right: 10px \">
            <h1 style=\"font-size: 2em\">Failed</h1>
          <strong>Application: ${{ inputs.app-name }}:${{ inputs.version }} release failed</strong>
          </div>"
        }' https://telicentio.webhook.office.com/webhookb2/${{ inputs.teams-channel-connector-hash }}
