name: Build and Push Container Image
description: Build, tag and push a container image to the selected container repository
author: Telicent

inputs:
  app-name:
    required: true
    description: The name for the application used as the main portion of the image name.
  app-name-prefix:
    required: false
    default: telicent-
    description: The prefix for the image name, defaults to 'telicent-'.
  dry-run:
    required: false
    default: 'false'
    description: Whether to test the build and scan without pushing to the registry.
  github-token:
    required: true
    description: GitHub token to allow the action to interact with the repository.

  # Application build options
  enable-buildkit-cache:
    required: false
    default: 'false'
    description: Whether the docker buildkit cache is required.
  java-version:
    required: false
    default: '21'
    description: Specifies the JDK version to install and build with.  Defaults to 21.
  jdk:
    required: false
    default: temurin
    description: Specifies the JDK to use, defaults to temurin.
  package-directory:
    required: false
    default: .
    description: If release has multiple package that are SBOM targets, then set this to disambiguate SBOMs.
  uses-maven:
    required: false
    default: 'false'
    description: Whether your build requires the JDK and Maven to be present.

  # Container registry options
  registry:
    required: true
    description: The container registry to push the image to. Supported values are 'aws' (Amazon ECR) or 'quay' (Quay.io).
  quay-username:
    required: false
    description: Quay username.
  quay-token:
    required: false
    description: Quay token.

  # Container build and tag options
  allow-mutable-tags:
    required: false
    default: 'true'
    description: Set to `false` to avoid adding mutable tags like `latest` and `development`.
  allow-sha-tag:
    required: false
    default: 'true'
    description: Set to 'false' to avoid adding the image SHA as a tag.
  allow-version-tag:
    required: false
    default: 'true'
    description: Set to 'false' to avoid adding a version tag.
  build-args:
    required: false
    description: Additional build arguments to pass to the Docker --build-arg flag.
  build-artifact:
    required: false
    description: Artifact used as part of the Docker build.
  dockerfile:
    required: true
    description: The name of the Dockerfile to build the image from.
  image-suffix:
    required: false
    description: Optional suffix used as part of the image name.
  main-branch:
    required: false
    default: main
    description: |
      Specifies the main branch for the repository, defaults to main.  If this build is on the configured main
      branch then the latest tag will be added to the image, if the build is on another branch then the development
      tag will be added to the image (only with `ALLOW_MUTABLE_TAGS` for both).
  path:
    description: The path in which the Dockerfile is located. For current path leave empty. Otherwise eg. ./frontend
    default: .
  target:
    required: false
    description: The build target within the Dockerfile to build the image from.
  version:
    required: true
    description: The version for the image, used in tagging the image.
  version-suffix:
    required: false
    description: Optional suffix for the version of the image, used in tagging the image.

  # MS Teams notification options
  teams-channel-connector-hash:
    required: false
    description: The connector hash generated by the incoming webhook plugin in MS TEAMS

  # Trivy/Grype scanning options
  grype-scan-image:
    required: false
    default: 'true'
    description: Whether to run a Grype scan on the built image.
  trivy-ignores:
    required: false
    description: Name of trivy ignore file. Only allowed for BUILD image, MUST NOT be used with DEPLOY images.
  trivy-scan-dockerfile:
    required: false
    default: 'true'
    description: Whether to run a Trivy scan on the Dockerfile used to build the image.
  trivy-scan-image:
    required: false
    default: 'true'
    description: Whether to run a Trivy scan on the built image.
  fail-on-unfixed:
    required: false
    default: 'false'
    description: Whether to fail the scan if unfixed vulnerabilities are found.
  remote-vex:
    required: false
    description: |
      Supplies references to one/more repositories from which additional VEX statements should be obtained and used
      to filter out vulnerabilities that have been assessed as to not apply to our software products.
      Note that telicent-oss/telicent-base-images is always included by default so this is only needed if the image
      being built relies on other images/libraries for which VEX statements are required.


  # Build secrets
  font-awesome-key:
    required: false
    description: NPM Font Awesome token.
  package-pat:
    required: false
    description: NPM package feed token.
outputs:
  image:
    description: The versioned container image tag that was created and published.
    value: ${{ steps.capture-tags.outputs.image }}

runs:
  using: composite
  steps:

    - name: Validate registry inputs
      uses: telicent-oss/shared-workflows/.github/actions/validate-registry-inputs@main
      with:
        registry: "${{ inputs.registry }}"
        quay-username: "${{ inputs.quay-username }}"
        quay-token: "${{ inputs.quay-token }}"

    # Set some globals, as environment variables are not allowed in composite actions.
    - name: Set globals
      id: globals
      run: ${{ github.action_path }}/globals.sh
      shell: bash
      env:
        BOM_ARTIFACT_NAME: "${{ github.run_number }}${{ inputs.package-directory != '.' && format('-{0}', inputs.package-directory) || '' }}.sbom.json"

    - name: Checkout
      uses: actions/checkout@v5

    - name: Install Java and Maven
      if: ${{ inputs.uses-maven == 'true' }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java-version }}
        distribution: ${{ inputs.jdk }}
        cache: maven

    # NB - Assumption here is that this workflow has been called after the Maven workflow has been called so the
    #      Maven Cache already has all our dependencies present in it and tests have already passed
    - name: Quick Maven Build
      if: ${{ inputs.uses-maven == 'true' }}
      run: mvn package -U --batch-mode -DskipTests
      shell: bash

    - name: Download build artifact
      uses: actions/download-artifact@v4
      if: ${{ inputs.build-artifact }}
      with:
        name: ${{ inputs.build-artifact }}
        path: ${{ inputs.build-artifact }}/

    - name: Get SBOM from artifact
      uses: actions/download-artifact@v4
      # Allow to continue even if SBOM is not found
      continue-on-error: true
      with:
        name: ${{ steps.global.outputs.bom-artifact-name }}
        path: ${{ inputs.PATH }}

    - name: Enable buildkit cache
      uses: actions/cache@v4.2.0
      if: ${{ inputs.enable-buildkit-cache == 'true' }}
      with:
        path: /tmp/buildkit-cache/buildkit-state.tar
        key: ${{ runner.os }}-buildkit-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildkit-

    - name: Load buildkit state from cache
      uses: dashevo/gh-action-cache-buildkit-state@v1
      if: ${{ inputs.enable-buildkit-cache == 'true' }}
      with:
        builder: buildx_buildkit_${{ steps.buildx.outputs.name }}0
        cache-path: /tmp/buildkit-cache
        cache-max-size: 3g

    - name: Configure AWS credentials from main account
      if: ${{ inputs.registry == 'aws' && inputs.dry-run == 'false' && github.actor != 'dependabot[bot]' }}
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::098669589541:role/GitHubDeploymentRole
        aws-region: eu-west-2
        mask-aws-account-id: false

    - name: Docker Login to Amazon ECR
      # Only login if dry run is explicitly set to 'false'.
      # Dependabot triggered PRs don't have credentials to push images, so no need to login in this case either.
      if: ${{ inputs.registry == 'aws' && inputs.dry-run == 'false' && github.actor != 'dependabot[bot]' }}
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        mask-password: true

    - name: Docker Login to Quay
      # Only login if dry run is explicitly set to 'false'.
      # Dependabot triggered PRs don't have credentials to push images, so no need to login in this case either.
      if: ${{ inputs.registry == 'quay' && inputs.dry-run == 'false' && github.actor != 'dependabot[bot]' }}
      uses: docker/login-action@v3
      with:
        registry: quay.io
        username: ${{ inputs.quay-username }}
        password: ${{ inputs.quay-token }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: all

    - name: Set up Docker buildx
      id: buildx
      uses: docker/setup-buildx-action@v3

    - name: Prepare Docker image names and tags
      id: meta
      uses: docker/metadata-action@v5
      with:
        # Defines the base image names in repository/name format
        images: |
          ${{ env.AWS_REGISTRY }}${{ env.QUAY_REGISTRY }}/${{ env.IMAGE_NAME }}
        # Manually handling latest below so disabling automatic latest handling
        flavor: |
          latest=false
        tags: |
          type=ref,event=tag
          type=sha,format=long,prefix=,enable=${{ inputs.allow-sha-tag == 'true' }}
          type=semver,pattern={{{{version}}}},enable=${{ inputs.allow-version-tag == 'true' }}
          type=raw,value=${{ inputs.version }}${{ inputs.version-suffix }},enable=${{ inputs.allow-version-tag == 'true' }}
          type=raw,value=latest,enable=${{ inputs.allow-mutable-tags == 'true' && github.ref_name == inputs.main-branch }}
          type=raw,value=development,enable=${{ inputs.allow-mutable-tags == 'true' && github.ref_name != inputs.main-branch}}
      env:
        AWS_REGISTRY: ${{ inputs.registry == 'aws' && steps.login-ecr.outputs.registry || '' }}
        QUAY_REGISTRY: ${{ inputs.registry == 'quay' && 'quay.io/telicent' || '' }}
        IMAGE_NAME: ${{ inputs.app-name-prefix }}${{ inputs.app-name }}${{ inputs.image-suffix }}

    - name: Build, tag, and push container image
      id: build-images
      uses: docker/build-push-action@v6
      # Only build, tag and push image if dry run is explicitly set to 'false'.
      if: ${{ inputs.dry-run == 'false' }}
      env:
        DOCKER_BUILDKIT: 1
      with:
        builder: ${{ steps.buildx.outputs.name }}
        platforms: linux/amd64,linux/arm64
        # Dependabot triggered PRs don't have credentials to push images.
        push: ${{ github.actor != 'dependabot[bot]' }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        context: ${{ inputs.path }}
        file: ${{ inputs.path }}/${{ inputs.dockerfile }}
        tags: ${{ steps.meta.outputs.tags }}
        target: ${{ inputs.target }}
        secrets: |
          npmTokenId=${{ inputs.package-pat }}
          fontAwesomeTokenId=${{ inputs.font-awesome-key }}
        build-args: |
          ${{ inputs.build-args }}

    - name: Build container image tarball (dry run)
      id: build-images-dry-run
      uses: docker/build-push-action@v6
      # Build a tarball if dry run is not explicitly set to 'false'.
      if: ${{ inputs.dry-run != 'false' }}
      env:
        DOCKER_BUILDKIT: 1
      with:
        builder: ${{ steps.buildx.outputs.name }}
        push: false
        cache-from: type=gha
        cache-to: type=gha,mode=max
        context: ${{ inputs.path }}
        file: ${{ inputs.path }}/${{ inputs.dockerfile }}
        tags: ${{ steps.meta.outputs.tags }}
        target: ${{ inputs.target }}
        secrets: |
          npmTokenId=${{ inputs.package-pat }}
          fontAwesomeTokenId=${{ inputs.font-awesome-key }}
        build-args: |
          ${{ inputs.build-args }}
        # The default image store in Docker Engine doesn't support loading multi-platform images.
        # Because of this, the dry run excludes the 'platforms' input.
        outputs: type=docker,dest=/tmp/${{ inputs.app-name-prefix }}${{ inputs.app-name }}${{ inputs.image-suffix }}.tar

    - name: Upload container image tarball artefact
      id: upload-image-artefact
      uses: actions/upload-artifact@v4
      # Tarball to upload as an artefact is created if dry run is not explicitly set to 'false'.
      if: ${{ inputs.dry-run != 'false' }}
      with:
        name: ${{ inputs.APP_NAME_PREFIX }}${{ inputs.APP_NAME }}${{ inputs.IMAGE_SUFFIX }}.tar
        path: /tmp/${{ inputs.APP_NAME_PREFIX }}${{ inputs.APP_NAME }}${{ inputs.IMAGE_SUFFIX }}.tar

    - name: Capture built container image tags
      id: capture-tags
      run: ${{ github.action_path }}/capture-tags.sh
      shell: bash
      env:
        REGISTRY: "${{ inputs.registry }}"
        AWS_REGISTRY_URL: "${{ steps.login-ecr.outputs.registry}}"
        QUAY_REGISTRY_URL: "quay.io/telicent"
        IMAGE_NAME: "${{ inputs.app-name-prefix }}${{ inputs.app-name }}${{ inputs.image-suffix }}"
        IMAGE_VERSION: "${{ steps.meta.outputs.version }}"

    - name: Trivy dockerfile scan
      if: ${{ inputs.trivy-scan-dockerfile == 'true' }}
      uses: telicent-oss/shared-workflows/.github/actions/trivy-dockerfile-scan@main
      with:
        dockerfile: ${{ inputs.path }}/${{ inputs.dockerfile }}
        github-token: ${{ inputs.github-token }}
        scan-name: ${{ inputs.app-name-prefix }}${{ inputs.app-name }}${{ inputs.image-suffix }}-${{ inputs.dockerfile }}

    - name: Trivy image scan
      # Dependabot triggered PRs don't have credentials to push images, so there won't be an image to scan.
      if: ${{ inputs.trivy-scan-image == 'true' && github.actor != 'dependabot[bot]' }}
      uses: telicent-oss/shared-workflows/.github/actions/trivy-image-scan@TELDEVOPS-880-update-actions-for-oss
      with:
        github-token: ${{ inputs.github-token }}
        image-ref: ${{ steps.capture-tags.outputs.image }}
        registry: ${{ inputs.registry }}
        quay-username: ${{ inputs.quay-username }}
        quay-token: ${{ inputs.quay-token }}
        scan-name: ${{ inputs.app-name-prefix }}${{ inputs.app-name }}${{ inputs.image-suffix }}-${{ inputs.dockerfile }}
        fail-on-unfixed: ${{ inputs.fail-on-unfixed }}
        remote-vex: ${{ inputs.remote-vex }}
        trivy-ignores: ${{ inputs.trivy-ignores != '' && format('{0}/{1}', inputs.package-directory, inputs.trivy-ignores) || '' }}

    - name: Grype image scan
      # Dependabot triggered PRs don't have credentials to push images, so there won't be an image to scan.
      if: ${{ inputs.grype-scan-image == 'true' && github.actor != 'dependabot[bot]' }}
      uses: telicent-oss/shared-workflows/.github/actions/grype-image-scan@TELDEVOPS-880-update-actions-for-oss
      with:
        github-token: ${{ inputs.github-token }}
        image-ref: ${{ steps.capture-tags.outputs.image }}
        registry: ${{ inputs.registry }}
        quay-username: ${{ inputs.quay-username }}
        quay-token: ${{ inputs.quay-token }}
        scan-name: ${{ inputs.app-name-prefix }}${{ inputs.app-name }}${{ inputs.image-suffix }}-${{ inputs.dockerfile }}
        fail-on-unfixed: ${{ inputs.fail-on-unfixed }}
        remote-vex: ${{ inputs.remote-vex }}

    - name: Notify MS Teams
      if: always()
      uses: telicent-oss/shared-workflows/.github/actions/notify-teams@main
      with:
        app-name: ${{ inputs.app-name-prefix }}${{ inputs.app-name }}${{ inputs.image-suffix }}-${{ inputs.dockerfile }}
        version: ${{ inputs.version }}${{ inputs.version-suffix }}
        status: ${{ steps.build.result }}
        image: ${{ steps.capture-tags.outputs.image }}
        teams-channel-connector-hash: ${{ inputs.teams-channel-connector-hash }}
