name: Lint And Unit Tests Helm Charts
description: |
  Lint a Helm chart, and any sub-charts, in the given path using `helm lint`.
  This action is intended to be used in a workflow that runs on pull requests to
  validate that any changes to Helm charts are valid and follow best practices.
author: Telicent

inputs:
  chart:
    required: true
    description: Path to the Helm chart to lint, relative to the repository root.
  test-mode:
    required: false
    default: union
    description: One of "local-only", "shared-only", or "union".

runs:
  using: composite
  steps:
    - name: Checkout Helm chart
      uses: actions/checkout@v6
      with:
        sparse-checkout: ${{ inputs.chart }}
        sparse-checkout-cone-mode: false
    - name: Install Helm
      uses: azure/setup-helm@v4
      with:
        version: "latest"
    - name: Lint Helm charts
      shell: bash
      run: helm lint ${{ inputs.chart }}
    - name: Install helm-unittest
      shell: bash
      run: |
        helm plugin install https://github.com/helm-unittest/helm-unittest.git --verify=false
    - name: DEBUG - inspect action path
      shell: bash
      run: |
        echo "action_path is: ${{ github.action_path }}"
        ls -la "${{ github.action_path }}"
        echo "---"
        ls -la "${{ github.action_path }}/shared-tests" || echo "shared-tests directory does not exist"
    - name: Run Helm chart tests
      shell: bash
      run: |
        "${{ github.action_path }}/run-helm-tests.sh" \
          "${{ inputs.chart }}" \
          "${{ inputs.test-mode }}" \
          "${{ github.action_path }}"