name: Scan Container Image with Trivy
description: Scan a container image for vulnerabilities using Trivy
author: Telicent

# Requires permissions -
# - contents: write
# - id-token: write

inputs:
  # Scan options
  image-ref:
    required: true
    description: |
      Specifies the full image reference (repository, name and tag) for an image you wish to scan.
  scan-name:
    required: true
    description: |
      A developer friendly name for the image to differentiate scan reports where a repository is
      building multiple images.
  trivy-ignores:
    required: true
    description: Only allowed for BUILD image, MUST NOT be used with DEPLOY image. Full relative path to trivy ignore file.

  # Container registry options
  registry:
    required: true
    description: The container registry to push the image to. Supported values are 'aws' (Amazon ECR) or 'quay' (Quay.io).
  quay-username:
    required: false
    description: Quay username.
  quay-token:
    required: false
    description: Quay token.

runs:
  using: composite
  steps:

    - name: Validate registry inputs
      uses: telicent-io/telicent-test/.github/actions/validate-registry-inputs@main
      with:
        registry: "${{ inputs.registry }}"
        quay-username: "${{ inputs.quay-username }}"
        quay-token: "${{ inputs.quay-token }}"

    - name: Checkout
      uses: actions/checkout@v5

    - name: Configure AWS credentials from main account
      if: ${{ inputs.registry == 'aws' }}
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::098669589541:role/GitHubDeploymentRole
        aws-region: eu-west-2
        mask-aws-account-id: false

    - name: Login to Amazon ECR
      if: ${{ inputs.registry == 'aws' }}
      uses: aws-actions/amazon-ecr-login@v1
      with:
        mask-password: true

    - name: Docker Login to Quay
      if: ${{ inputs.registry == 'quay' }}
      uses: docker/login-action@v2
      with:
        registry: quay.io
        username: ${{ inputs.quay-username }}
        password: ${{ inputs.quay-token }}

    - name: Trivy Vulnerability Scan
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: "image"
        image-ref: ${{ inputs.image-ref }}
        output: trivy-docker-report.json
        format: json
        exit-code: 0
        trivyignores: ${{ inputs.trivy-ignores }}

    - name: Upload Vulnerability Scan Results
      uses: actions/upload-artifact@v4
      with:
        name: trivy-docker-report-${{ inputs.scan-name }}
        path: trivy-docker-report.json
        retention-days: 30

    - name: Generate SBOM for image (IF has tags for release)
      if: startsWith(github.ref, 'refs/tags/')
      uses: aquasecurity/trivy-action@0.20.0
      with:
        scan-type: 'image'
        format: 'cyclonedx'
        output: trivy-image-scan-sbom-${{ inputs.scan-name }}.json
        image-ref: ${{ inputs.image-ref }}

    - name: Release SBOM for image (IF has tags for release)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: |
          trivy-image-scan-sbom-${{ inputs.scan-name }}.json

    - name: Release report on docker sbom (IF has tags for release)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: |
          trivy-docker-report.json

    - name: Fail Build on High/Critical Vulnerabilities
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: "image"
        image-ref: ${{ inputs.image-ref }}
        format: table
        severity: HIGH,CRITICAL
        ignore-unfixed: true
        exit-code: 1
        trivyignores: ${{ inputs.trivy-ignores }}
