name: Scan Container Image with Trivy
description: Scan a container image for vulnerabilities using Trivy
author: Telicent

# Requires permissions -
# - contents: write
# - id-token: write

inputs:
  # Scan options
  image-ref:
    required: true
    description: |
      Specifies the full image reference (repository, name and tag) for an image you wish to scan.
  image-from-artefact:
    required: false
    default: 'false'
    description: Whether to scan an image artefact (e.g. a tar file), rather than an image in a remote repository.
  scan-name:
    required: true
    description: |
      A developer friendly name for the image to differentiate scan reports where a repository is
      building multiple images.
  trivy-ignores:
    required: false
    description: Only allowed for BUILD image, MUST NOT be used with DEPLOY image. Full relative path to trivy ignore file.
  fail-on-unfixed:
    required: false
    default: "false"
    description: Whether to fail the scan if unfixed vulnerabilities are found.
  remote-vex:
    required: false
    description: |
      Supplies references to one/more repositories from which additional VEX statements should be obtained and used
      to filter out vulnerabilities that have been assessed as to not apply to our software products.

      Note that telicent-oss/telicent-base-images is always included by default so this is only needed if the image
      being built relies on other images/libraries for which VEX statements are required.
  uses-java:
    required: false
    default: "false"
    description: |
      Indicates whether the image includes Java artifacts, we need to know this in order to determine which Trivy
      vulnerability databases to obtain.
  github-token:
    required: true
    description: GitHub token to allow the action to interact with the repository.

  # Container registry options
  registry:
    required: true
    description: The container registry to push the image to. Supported values are 'aws' (Amazon ECR) or 'quay' (Quay.io).
  quay-username:
    required: false
    description: Quay username.
  quay-token:
    required: false
    description: Quay token.

runs:
  using: composite
  steps:

    - name: Validate registry inputs
      uses: telicent-oss/shared-workflows/.github/actions/validate-registry-inputs@main
      with:
        registry: "${{ inputs.registry }}"
        quay-username: "${{ inputs.quay-username }}"
        quay-token: "${{ inputs.quay-token }}"

    - name: Checkout
      uses: actions/checkout@v5

    - name: Configure AWS credentials from main account
      if: ${{ inputs.registry == 'aws' && inputs.image-from-artefact == 'false' }}
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::098669589541:role/GitHubDeploymentRole
        aws-region: eu-west-2
        mask-aws-account-id: true

    - name: Login to Amazon ECR
      if: ${{ inputs.registry == 'aws' && inputs.image-from-artefact == 'false' }}
      uses: aws-actions/amazon-ecr-login@v1
      with:
        mask-password: true

    - name: Docker Login to Quay
      if: ${{ inputs.registry == 'quay' && inputs.image-from-artefact == 'false' }}
      uses: docker/login-action@v3
      with:
        registry: quay.io
        username: ${{ inputs.quay-username }}
        password: ${{ inputs.quay-token }}

    - name: Download image artifact
      uses: actions/download-artifact@v4
      if: ${{ inputs.image-from-artefact == 'true' }}
      with:
        name: ${{ inputs.scan-name }}.tar
        path: .

    - name: Load docker image for dry run scans
      if: ${{ inputs.image-from-artefact == 'true' }}
      run: docker load --input ${{ inputs.scan-name }}.tar
      shell: bash

    - name: Trivy vulnerability scan
      id: trivy-scan
      uses: telicent-oss/trivy-action@v1
      env:
        TRIVY_IGNOREFILE: ${{ inputs.trivy-ignores }}
      with:
        gh-token: ${{ inputs.github-token }}
        scan-type: image
        scan-name: docker-${{ inputs.scan-name }}
        scan-ref: ${{ inputs.image-ref }}
        uses-java: ${{ inputs.uses-java }}
        allow-unfixed: ${{ inputs.fail-on-unfixed == 'false' }}
        remote-vex: |
          telicent-oss/telicent-base-images
          ${{ inputs.remote-vex }}
        output-sbom: ${{ startsWith(github.ref, 'refs/tags/') && 'release' || '' }}

    - name: Release SBOM for image (If has tags for release)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2.4.1
      with:
        files: |
          ${{ runner.temp }}/${{ steps.trivy-scan.outputs.sbom-file }}

    - name: Release report on docker sbom (If has tags for release)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2.4.1
      with:
        files: |
          ${{ steps.trivy-scan.outputs.scan-results-file }}
