name: Prepare Python Application
description: Checkout code and install pip dependencies for a python project.

inputs:
  version:
    required: true
    description: The python version to test and build against.
  extra-args:
    required: false
    description: Any extra arguments to pass to the pip-compile tool when generating a requirements file.
  install-requirements:
    required: false
    default: 'false'
    description: Whether to install packages defined in the generated requirements file.
  pyproject-toml-path:
    required: false
    default: pyproject.toml
    description: |
      Path to the pyproject.toml file, relative to the repository root.
      Defaults to `pyproject.toml`.

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: Set up Python ${{ inputs.version }}
      uses: actions/setup-python@v5.6.0
      with:
        python-version: ${{ inputs.version }}
    - name: Prepare pip and install pip-tools
      shell: ${{ runner.os == 'Windows' && 'pwsh' || 'bash' }}
      run: |
        python -m pip install --upgrade "pip<25.3"
        python -m pip install pip-tools
    - name: Generate requirements
      shell: ${{ runner.os == 'Windows' && 'pwsh' || 'bash' }}
      run: python -m piptools compile ${{ inputs.extra-args }} -o requirements.txt ${{ inputs.pyproject-toml-path }}
    - name: Install requirements
      if: inputs.install-requirements == 'true'
      shell: ${{ runner.os == 'Windows' && 'pwsh' || 'bash' }}
      run: pip install -r requirements.txt
