name: Python Tests for Python Applications and Libraries
description: |
  Run tests and build Python applications and libraries.
  This action is intended to be used in a workflow that runs on pull requests to
  validate that any changes to Python code do not break tests, and that the code
  can be built successfully (if applicable).
author: Telicent

inputs:
  code-artefact-role:
    required: true
    description: The ARN of the AWS IAM role to assume for accessing CodeArtifact.
  pyproject-toml-path:
    required: false
    default: pyproject.toml
    description: |
      Path to the pyproject.toml file, relative to the repository root.
      Defaults to `pyproject.toml`.
  skip-build:
    required: false
    default: 'false'
    description: Whether to skip the build test (i.e. for non-libraries).
  test-command:
    required: false
    default: "python -m unittest discover --verbose"
    description: The command to run when executing tests.
  version:
    required: true
    description: The python version to test and build against.

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: Set up Python ${{ inputs.version }}
      uses: actions/setup-python@v5.6.0
      with:
        python-version: ${{ inputs.version }}
    - name: Prepare pip and and pip-tools
      shell: ${{ runner.os == 'Windows' && 'pwsh' || 'bash' }}
      run: |
        python -m pip install --upgrade "pip<25.3"
        python -m pip install pip-tools
    - name: Configure CodeArtifact AWS credentials
      id: creds
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.code-artefact-role }}
        aws-region: eu-west-2
        mask-aws-account-id: true
    - name: CodeArtifact login
      uses: Telicent-io/aws-codeartifact-login-action@v1
      with:
        domain: telicent
        owner: ${{ steps.creds.outputs.aws-account-id }}
    - name: Generate requirements
      shell: ${{ runner.os == 'Windows' && 'pwsh' || 'bash' }}
      run: |
        python -m piptools compile --all-extras -o requirements.txt ${{ inputs.pyproject-toml-path }}
        pip install -r requirements.txt
      env:
        PIP_EXTRA_INDEX_URL: "https://aws:${{ env.AWS_CODEARTIFACT_TOKEN }}@telicent-${{ steps.creds.outputs.aws-account-id }}.d.codeartifact.eu-west-2.amazonaws.com/pypi/telicent-code-artifacts/simple/"
    - name: mypy static type checking
      shell: ${{ runner.os == 'Windows' && 'pwsh' || 'bash' }}
      run: python -m mypy
    - name: ruff python style checking
      shell: ${{ runner.os == 'Windows' && 'pwsh' || 'bash' }}
      run:  python -m ruff check --output-format=github .
    - name: Unit tests
      shell: ${{ runner.os == 'Windows' && 'pwsh' || 'bash' }}
      run: ${{ inputs.test-command }}
    - name: Build
      if: ${{ inputs.skip-build == 'false' }}
      shell: ${{ runner.os == 'Windows' && 'pwsh' || 'bash' }}
      run: python -m build