name: Python Tests for Python Applications and Libraries
description: |
  Run tests and build Python applications and libraries.
  This action is intended to be used in a workflow that runs on pull requests to
  validate that any changes to Python code do not break tests, and that the code
  can be built successfully (if applicable).
author: Telicent

inputs:
  version:
    required: true
    description: The python version to test and build against.
  code-artefact-role:
    required: false
    description: The ARN of the AWS IAM role to assume for accessing CodeArtifact.
  pyproject-toml-path:
    required: false
    default: pyproject.toml
    description: |
      Path to the pyproject.toml file, relative to the repository root.
      Defaults to `pyproject.toml`.
  skip-build:
    required: false
    default: 'false'
    description: Whether to skip the build test (i.e. for non-libraries).
  test-command:
    required: false
    default: "python -m unittest discover --verbose"
    description: The command to run when executing tests.
  extra-args:
    required: false
    description: Any extra dependencies to be included in SBOM scan.

runs:
  using: composite
  steps:
    - name: Prepare Python
      uses: telicent-oss/shared-workflows/.github/actions/python-prepare@TELICENT-1005-lddf-ontology-deployment
      with:
        code-artefact-role: ${{ inputs.code-artefact-role}}
        version: ${{ inputs.version }}       
    - name: Static type checking - mypy
      shell: ${{ runner.os == 'Windows' && 'pwsh' || 'bash' }}
      run: python -m mypy
    - name: Style checking - ruff
      shell: ${{ runner.os == 'Windows' && 'pwsh' || 'bash' }}
      run:  python -m ruff check --output-format=github .
    - name: Unit tests
      shell: ${{ runner.os == 'Windows' && 'pwsh' || 'bash' }}
      run: ${{ inputs.test-command }}
    - name: Build
      if: ${{ inputs.skip-build == 'false' }}
      shell: ${{ runner.os == 'Windows' && 'pwsh' || 'bash' }}
      run: python -m build