name: Package and Push Helm Chart
description: |
  Package and push a Helm chart to the selected Helm repository.
  Optionally update the chart version and app version prior to packaging.
author: Telicent

inputs:
  app-name:
    required: true
    description: The name for the application, used as the main portion of the Helm chart name.
  app-name-prefix:
    required: false
    default: telicent-
    description: The prefix for the Helm chart name. Defaults to `telicent-`.
  chart:
    required: true
    description: Path to the Helm chart to package and push, relative to the repository root.
  dry-run:
    required: false
    default: 'false'
    description: Whether to test the build and scan without pushing to the registry.

  # Container registry options
  registry:
    required: true
    description: The container registry to push the image to. Supported values are `aws` (Amazon ECR) or `quay` (Quay.io).
  quay-username:
    required: false
    description: Quay username. Required if registry is set to `quay`.
  quay-token:
    required: false
    description: Quay token. Required if registry is set to `quay`.

  # Chart packaging options
  version:
    required: true
    description: The version of the chart.
  appVersion:
    required: false
    description: |
      The app version to apply to the Chart.yaml when packaging the Helm chart.
      Ignored if `replace-chart-version` is not `true`.
  replace-chart-versions:
    required: false
    default: 'false'
    description: Whether the `version`` and `appVersion` values should be used to update Chart.yaml when packaging the Helm chart.

runs:
  using: composite
  steps:
    - name: Validate registry inputs
      uses: telicent-oss/shared-workflows/.github/actions/validate-registry-inputs@main
      with:
        registry: "${{ inputs.registry }}"
        quay-username: "${{ inputs.quay-username }}"
        quay-token: "${{ inputs.quay-token }}"
    - name: Install Helm
      uses: azure/setup-helm@v4
      with:
        version: "latest"
    - name: Package Helm chart
      shell: bash
      run: |
        echo "Packaging ${{ inputs.chart }}"
        if [[ "${{ inputs.replace-chart-version }}" == 'true' ]]; then
          echo "  🔄 Updating chart version and app version to ${{ inputs.version }}"
          helm package "${{ inputs.chart }}" --destination "${{ runner.temp }}/packaged-chart/" \
            --version "${{ inputs.version }}" \
            --app-version "${{ inputs.appVersion != '' && inputs.appVersion || inputs.version }}"
        else
          helm package "${{ inputs.chart }}" --destination "${{ runner.temp }}/packaged-chart/"
        fi

    ###
    # Steps if action is a dry run, i.e. the Helm chart should not be pushed
    ###
    - name: Upload container image tarball artefact
      # Only run if dry run is set to anything other than 'false', indicating that this is a dry run
      id: upload-image-artefact
      uses: actions/upload-artifact@v4
      if: ${{ inputs.dry-run != 'false' }}
      with:
        name: ${{ inputs.APP_NAME_PREFIX }}${{ inputs.APP_NAME }}${{ inputs.IMAGE_SUFFIX }}.tar
        path: /tmp/${{ inputs.APP_NAME_PREFIX }}${{ inputs.APP_NAME }}${{ inputs.IMAGE_SUFFIX }}.tar

    ###
    # Steps if action is not a dry run, i.e. the Helm chart should actually be pushed
    ###
    - name: Configure AWS credentials from main account
      # Only run if dry run is explicitly set to 'false'
      # Dependabot triggered PRs don't have credentials to push Helm charts, so no need to run in this case either
      if: ${{ inputs.registry == 'aws' && inputs.dry-run == 'false' && github.actor != 'dependabot[bot]' }}
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::098669589541:role/GitHubDeploymentRole
        aws-region: eu-west-2
        mask-aws-account-id: false
    - name: Docker Login to Amazon ECR
      # Only run if dry run is explicitly set to 'false'
      # Dependabot triggered PRs don't have credentials to push Helm charts, so no need to run in this case either
      if: ${{ inputs.registry == 'aws' && inputs.dry-run == 'false' && github.actor != 'dependabot[bot]' }}
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        mask-password: true
    - name: Log in to Quay.io (Helm)
      # Only run if dry run is explicitly set to 'false'
      # Dependabot triggered PRs don't have credentials to push Helm charts, so no need to run in this case either
      if: ${{ inputs.registry == 'quay' && inputs.dry-run == 'false' && github.actor != 'dependabot[bot]' }}
      shell: bash
      run: |
        echo "$QUAY_TOKEN" | helm registry login quay.io --username "$QUAY_USERNAME" --password-stdin
      env:
        QUAY_USERNAME: ${{ inputs.quay-username }}
        QUAY_TOKEN: ${{ inputs.quay-token }}
    - name: Checkout Helm chart
      uses: actions/checkout@v6
      with:
        sparse-checkout: ${{ inputs.chart}}
        sparse-checkout-cone-mode: false
    - name: Push Helm chart
      # Only run if dry run is explicitly set to 'false'
      if: ${{ inputs.dry-run == 'false' }}
      shell: bash
      run: |
          echo "Pushing Helm chart "$chart" to ${{ env.AWS_REGISTRY }}${{ env.QUAY_REGISTRY }}"
          helm push "$PACKAGED_CHART" ${{ env.AWS_REGISTRY }}${{ env.QUAY_REGISTRY }}
          echo "  ✅ Helm chart pushed successfully"
      env:
        PACKAGED_CHART: "${{ runner.temp }}/packaged-chart/${{ inputs.app-name-prefix }}${{ inputs.app-name }}-${{ inputs.version }}.tgz"
        AWS_REGISTRY: ${{ inputs.registry == 'aws' && format('oci://{0}/charts' ,steps.login-ecr.outputs.registry) || '' }}
        QUAY_REGISTRY: ${{ inputs.registry == 'quay' && 'oci://quay.io/telicent/charts' || '' }}
