name: Maven Central Audit

on:
  workflow_call:
    inputs:
      MAVEN_REPOSITORY_ID:
        required: false
        type: string
        default: central
        description: |
          Specifies the ID of the repository to which `SNAPSHOT`s and Releases are published, this **MUST** match 
          the ID of a repository defined in the `pom.xml` for the project in order for credentials to be correctly 
          configured.
      JAVA_VERSION:
        required: false
        type: number
        default: 21
        description: |
          Specifies the JDK version to install and build with.  Defaults to 21.
      JDK:
        required: false
        type: string
        default: temurin
        description: |
          Specifies the JDK to use, defaults to `temurin`.
      MAIN_BRANCH:
        required: false
        type: string
        default: main
        description: |
          Specifies the main branch for the repository.

          Used in determining whether there are relevant changes that should trigger the Maven Central Audit.
    secrets:
      MVN_USER_NAME:
        required: false
        description: |
          Username for authenticating to a Maven repository to publish releases.
      MVN_USER_PWD:
        required: false
        description: |
          Password/Token for authenticating to a Maven repository to publish releases.
      GPG_PRIVATE_KEY:
        required: false
        description: |
          A GPG Private Key that will be used to sign the built artifacts during the build process.  The `pom.xml`
          **MUST** invoke the `maven-gpg-plugin` for this to have an effect.
      GPG_PASSPHRASE:
        required: false
        description: |
          The passphrase protecting the provided GPG Private Key.
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  maven-central-audit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    name: Maven Central Audit
    env:
      # These have to be exported into the environment due to how the setup-java action configures the Maven
      # settings.xml file to avoid directly embedding credentials into it.
      MAVEN_USERNAME: ${{ secrets.MVN_USER_NAME }}
      MAVEN_PASSWORD: ${{ secrets.MVN_USER_PWD }}
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v6.0.2

      - name: Install Java and Maven
        uses: actions/setup-java@v5.3.0
        with:
          java-version: ${{ inputs.JAVA_VERSION }}
          distribution: ${{ inputs.JDK }}
          cache: maven
          server-id: ${{ inputs.MAVEN_REPOSITORY_ID }}
          # Forced to use indirection here, the setup-java action configures the Maven settings.xml to reference
          # the credentials via environment variables
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v7.0.0
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      # Only changes to pom.xml files are likely to have significant changes on release size
      # While code changes will change release size marginally its only actual POM changes, e.g.,
      # introducing new modules, reconfiguring plugins etc. that are likely to cause substantial
      # changes in the release size
      #
      # Therefore by checking whether the POM files have changed we can avoid running the audit
      # on branches that don't affect this
      #
      # Note that we always run the audit on main branch builds as an ongoing sanity check.  There
      # are some non-POM changes that could cause substantial changes in the release size, e.g., a 
      # large resource file added to a module, but we expect those to be rare and generally developers
      # would spot those and query them during the PR reviews.
      - name: Check whether any POM files changed
        id: pom-changes
        uses: rvesse/detect-changes-action@v1
        with:
          base: ${{ inputs.MAIN_BRANCH }}
          pattern: pom.xml
          flags: -F
          # Ensures we always run audit when building on main
          output-on-base: true
          summary: false
          notices: false

      - name: Run Maven Central Audit
        if: ${{ steps.pom-changes.outputs.changed == 'true' }}
        uses: telicent-oss/mvn-central-audit@v1
        with:
          # Specify limits, if a release would be above this size then the build will be failed
          max-files: 600
          max-size: 16000000 # 16MB