name: Python Cyclone DX Scan

on:
  workflow_call:

jobs:
  generate-sbom:
    name: Generate SBOM
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Prepare pip and and pip-tools
      run: |
        python -m pip install --upgrade pip
        python -m pip install pip-tools

    - name: Generate requirements
      run: |
        python -m piptools compile -o requirements.txt pyproject.toml
        pip install cyclonedx-bom==4.4.3

    - name: Generate SBOM
      run: |
        python -m cyclonedx_py requirements > ${{ github.run_number }}-cyclone-dx.json

    - name: Store the SBOM
      uses: actions/upload-artifact@v3
      with:
        name: cyclone-dx-sbom
        path: ${{ github.run_number }}-cyclone-dx.json

  scan-sbom-for-high-crit:
    name: Scan SBOM for HIGH and CRITICAL
    needs:
    - generate-sbom
    runs-on: ubuntu-latest
    steps:
      - name: Download SBOM
        uses: actions/download-artifact@v3
        with:
          name: cyclone-dx-sbom
      - name: Scan SBOM
        uses: aquasecurity/trivy-action@master
        with:
          exit-code: '1'
          format: 'table'
          severity: 'HIGH,CRITICAL'
          scan-ref: ${{ github.run_number }}-cyclone-dx.json
          scan-type: 'sbom'
          scanners: 'vuln'

  scan-sbom-for-low-med:
    name: Scan SBOM for LOW and MEDIUM
    needs:
    - generate-sbom
    runs-on: ubuntu-latest
    steps:
      - name: Download SBOM
        uses: actions/download-artifact@v3
        with:
          name: cyclone-dx-sbom
      - name: Scan SBOM
        uses: aquasecurity/trivy-action@master
        with:
          exit-code: '0'
          format: 'table'
          severity: 'UNKNOWN,LOW,MEDIUM'
          scan-ref: ${{ github.run_number }}-cyclone-dx.json
          scan-type: 'sbom'
          scanners: 'vuln'
