name: Python Tests for Libraries

on:
  workflow_call:
    inputs:
      PYTHON_VERSION:
        required: true
        type: string
        description: The python version to test and build against
      TEST_COMMAND:
        required: false
        type: string
        description: The command to run for tests
        default: "python -m unittest discover --verbose"
      SKIP_BUILD:
        required: false
        type: boolean
        description: Whether to skip the build test (i.e. for non-libraries)
        default: false
  workflow_dispatch:

jobs:
  test_and_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ inputs.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.PYTHON_VERSION }}

      - name: Prepare pip and and pip-tools
        run: |
          python -m pip install --upgrade pip
          python -m pip install pip-tools

      - name: Generate requirements
        run: |
          python -m piptools compile --all-extras -o requirements.txt pyproject.toml
          pip install -r requirements.txt

      - name: mypy Static Type Checking
        run: python -m mypy

      - name: ruff Python Style Checking
        run:  python -m ruff check --output-format=github .

      - name: Unit Tests
        run: ${{ inputs.test_command }}

      - name: Build
        if: ${{ inputs.SKIP_BUILD == false }}
        run: python -m build
